### ISSUE TITLE
Line 51 (-ish) in JROmniFocus.m should be updated to exclude com.omnigroup.OmniFocus2.Today as a possible match

### ISSUE THREAD

**Issue by naupaka** [jyruzicka/JROFBridge#2]
I think this will fix issue #2 in the kanban-fetch repo, and make it work with the 2.1 beta builds of OF2 (and any future builds, since the 'Today' widget will probably be here to stay.
https://github.com/jyruzicka/kanban-fetch/issues/2

**Comment by jyruzicka** [comment]
Hey, check [this copy](https://dl.dropboxusercontent.com/u/1950386/Temp/kanban-fetch) out and let me know if it works proper-like.

**Comment by naupaka** [comment]
Yup, works now, thanks!! I also was able to make the older one work as well by disabling the OmniFocus Today widget in notification center on Yosemite.

**Comment by jyruzicka** [comment]
Cool! Appropriate changes made, and pushed.
